name: Generate

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - shell: pwsh
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if the file vangen.json has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^vangen.json$' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "changed"
          Write-Host "::set-output name=changed::$HasDiff"

      - if: ${{ steps.check_file_changed.outputs.changed == 'True' }}
        name: Set up Go 1.19.x
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # pin@v3
        with:
          go-version: "1.19.x"
        id: go

      - if: ${{ steps.check_file_changed.outputs.changed == 'True' }}
        name: Generate static HTML for Go repositories with a vanity import path
        run: |
          go install 4d63.com/vangen@v1.4.0
          cd $GITHUB_WORKSPACE
          vangen -out docs
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am "generated docs/DOC.md"
          git push -u origin HEAD:main
